//
// Created by maciej on 03.03.18.
//

#ifndef MULTIPLICATIONTABLE_MULTIPLICATIONTABLE_H
#define MULTIPLICATIONTABLE_MULTIPLICATIONTABLE_H

void MultiplicationTable(int tab[][10]);

#endif //MULTIPLICATIONTABLE_MULTIPLICATIONTABLE_H
